* [[file:archive.org][(2024-05-27) Posts Archive]]
(No preview)
* [[file:index.org][(2024-05-27) Javier Pacheco]]
(No preview)
* [[file:about.org][(2024-05-27) About Me]]
(No preview)
* posts
** [[file:posts/my_hyprland_config.org][(2024-05-27) My Hyprland Config]]
Hello, in this post I'm going to share and explain a little bit my =Hyprland= configuration, I'm not an expert in this window manager, but I really like it, I think this WM have a great future, and for me, this one is the best out there, of course there are some more, more solids if you will, but this is awesome.
** [[file:posts/emacs-fetching-tool-efetchel.org][(2024-01-14) Emacs Fetching tool - efetch.el]]
Embrace a new level of Emacs mastery with =efetch.el= – a powerful and user-friendly Emacs Fetching Tool. Designed for enthusiasts who crave insights into their Emacs environment, =efetch.el= provides a seamless way to peek under the hood of your setup. With just a simple command, unlock a left-side buffer showcasing key details such as Emacs version, host information, user details, installed packages, active theme, and default font. Customizable and accessible, this tool not only delivers a quick snapshot of your Emacs configuration but also opens the door for collaborative enhancements. Join the community on [[https://github.com/engjpacheco/efetch.el][GitHub]], contribute your ideas, and elevate your Emacs experience with =efetch.el= today!
** [[file:posts/export-org-files-to-html-and-clipboard.org][(2024-01-05) Copy html source from org files to the clipboard.]]
If you uses email a lot like me in your job, but also use emacs, you wonder if is possible
to export your org files to =html=, and paste in to your email, well, we are in emacs,
everything is possible within emacs, so in this post, I'll show you a couple of functions
that help me to make my workflow more efficient.
** [[file:posts/voidstrap-a-tui-void-linux-installator.org][(2024-01-01) Voidstrap a tui void linux installator]]
This is the first post of the 2024, this is a project that I am working on in the last
year, is a minimialist voidlinux instalator it is based in some recomendations in 
a guides that some friends of my have but "semiautomated".
** [[file:posts/copy-org-blocks-to-clipboard.org][(2023-12-29) Copy org blocks to clipboard]]
In this post I'll demostrate how to add a button to copy the content of a 
src block generated by ox-publish in emacs within org-mode, this script
create a button in every instance of codeblock in the html file that ox-publish
generate when create the web-page content.
** [[file:posts/attempt-to-test-rss-feeds.org][(2023-12-26) Attempt to test RSS feeds]]
Hello.

This post, is about  more like a testing, because, I'm trying to add RSS feeds into 
this "web-page", so basically this is a test, and see if when I build the webpage
is going to work... or not.
So, this is the preview and read this post to see what I'm trying to do.
** [[file:posts/denote-silo-function.org][(2023-12-25) Denote silo function]]
I have been reading some thing information about denote, and its powerful tools
that the good =prots= give to us the mortals. I am starting this "post" thing, and 
is good to have my notes apart from the posts that I'm going to write in the 
future, so reading I find a interesting function that prots suggest to use 
in the creation of notes.
** [[file:posts/themes-and-end-of-the-year.org][(2023-12-23) Themes and end of the year]]
This is the first of a few posts I'm creating this "web" only for my knowledge,
and contribute with some of it.

Some things are happening by a reason, so, instead of see the "bad" things that
happens; is a better practice to see the good side of the thing, these more or less
are some phrases that my dad says to me when me and my family have some problems.
** [[file:posts/test.org][(2023-12-23) Testing the build-site.]]
Probando el script para crear mi web page desde elisp