#+title: Themes updated
#+author: Javier Pacheco
#+date: [2024-05-28]
#+filetags: :personal:post:

#+BEGIN_PREVIEW
Some things are happening by a reason, so, instead of see the "bad" things that
happens; is a better practice to see the good side of the thing, these more or less
are some phrases that my dad says to me when me and my family have some problems.
#+END_PREVIEW

** Themes in emacs and end of the year.
:PROPERTIES:
:CUSTOM_ID: h:0f3ffdd6-6b21-4e10-a01b-ce72a618a1f5
:END:
I started to manage my themes, actually only one, I get rid off the /doom-themes/.
and add the atom-one-dark theme, lets see what will happens,
I actually like this theme the most, the only thing that is an issue from me
is the actual fonts management, so I'm going to "hack" this theme a little bit.

A end of another year is happening, this year  was a very though, health issues,
lack of money, lack of time, but at the end of the road, there is a minimal light
I hope that last call be the key, and hope this new year came with new challenges
and more opportunities.

This year I learn a lot of things, like:
- Emacs.
- nvim/vim.
- voidlinux.
- re-learn how to program a robot.
This ending year was a very good one, strong to get in trough but a very good one.
